### ISSUE TITLE
chebi roles

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/Experimental-OBO-Core#7]
CHEBI has a role hierarchy:

 * [CHEBI:50906](http://purl.obolibrary.org/obo/CHEBI_50906) ! role  
    * [CHEBI:24432](http://purl.obolibrary.org/obo/CHEBI_24432) ! biological role
    * [CHEBI:33232](http://purl.obolibrary.org/obo/CHEBI_33232) ! application
    * [CHEBI:51086](http://purl.obolibrary.org/obo/CHEBI_51086) ! chemical role

These are linked from structures via (their own) has-role relation. It could be useful to bring these in.

The challenge is:

 - it's not clear these are truly roles in the BFO sense
 - we need to 'knock out' CHEBI role and rewire the subclasses to whatever appropriate BFO class

Related: a while ago I tried axiomatizing all the CHEBI roles https://github.com/cmungall/chiro

**Comment by rctauber** [comment]
There is not a clear use case for ChEBI roles to be in core.
